apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: highpeaks-ml
  name: ml-platform-reader
rules:
- apiGroups: [""]
  resources: ["pods", "configmaps"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ml-platform-binding
  namespace: highpeaks-ml
subjects:
- kind: ServiceAccount
  name: default
  namespace: highpeaks-ml
roleRef:
  kind: Role
  name: ml-platform-reader
  apiGroup: rbac.authorization.k8s.io
