apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: highpeaks-devops
  name: devops-agent-reader
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devops-agent-binding
  namespace: highpeaks-devops
subjects:
- kind: ServiceAccount
  name: devops-agent-sa
  namespace: highpeaks-devops
roleRef:
  kind: Role
  name: devops-agent-reader
  apiGroup: rbac.authorization.k8s.io
