name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  validate-manifests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install kubectl
        run: |
          curl -sSLO https://dl.k8s.io/release/v1.26.0/bin/linux/amd64/kubectl
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/kubectl
      - name: Validate Kubernetes YAML in k8s/
        run: kubectl apply --dry-run=client -f k8s/
      - name: Validate deployment script with ShellCheck
        uses: ludeeus/action-shellcheck@v1
        with:
          files: run_highpeaks_deployment.sh
